name: iex_trading_client
description: A client for IEX Trading's REST API.
version: 0.0.1
#homepage: https://www.example.com
author: Jim Simon <jim.j.simon@gmail.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  http_client: ^0.5.0
  json_annotation: ^2.0.0

dev_dependencies:
  build_runner: ^1.1.2
  json_serializable: ^2.0.1
  test: ^1.5.1+1
